locations:
  tests: test/ply
  results:
    expected: test/ply/results/expected
    actual: test/ply/results/actual

files:
  requests:
    - '**/*.ply.yaml'
  cases:
    - '**/*.ply.ts'

response:
  # these are the headers we care about matching
  headers:
    - 'content-type'