# github workflow to build and test
name: 'build'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PLY_VALUES: ${{ secrets.PLY_VALUES }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - run: chmod +x dist/cli.js
    - run: npm test
